on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rustfmt:
    runs-on: macOS-latest
    name: rustfmt
    steps:
      - uses: actions/checkout@v6

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: cargo fmt
        run: cargo fmt --all -- --check

  test-stable:
    runs-on: macOS-latest
    name: cargo test stable
    steps:
      - uses: actions/checkout@v6

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cargo clippy
        run: cargo clippy -- -D warnings

      - name: cargo test
        run: cargo test
